### ISSUE TITLE
Error in compute_inverted_predication_index.py

### ISSUE THREAD

**Issue by HermannKroll** [HermannKroll/NarrativeIntelligence#219]
I updated the service on the weekend. The compute_inverted_predication_index.py script returned an error with the following output.

```
2023-09-18:14:09:51,307 INFO     [compute_reverse_index_predication.py:56] Starting...
denormalizing predication...: done in 0:05:05.507987 of 12998175) eta: 2023-09-18 14:15
2023-09-18:14:15:11,78 INFO     [compute_reverse_index_predication.py:95] Delta Mode activated - Only updating relevant inverted index entries
2023-09-18:14:16:31,939 INFO     [compute_reverse_index_predication.py:97] 43094381 entries are in the inverted index
Checking existing entries...... 67.3% done (28999000 of 43094381) eta: 2023-09-18 15:06
Checking existing entries...... 99.0% done (42644000 of 43094381) eta: 2023-09-18 15:07
Checking existing entries...: done in 1:02:59.3291170 of 43094381) eta: 2023-09-18 15:19
2023-09-18:15:19:31,269 INFO     [compute_reverse_index_predication.py:122] 2106058 inverted index entries must be deleted

2023-09-18:15:30:56,808 INFO     [compute_reverse_index_predication.py:125] Entries deleted
2023-09-18:15:30:56,812 INFO     [compute_reverse_index_predication.py:127] Compute insert...
insert values...... 45.4% done (1300000 of 2865221) eta: 2023-09-18 16:31Traceback (most recent call last):
  File "/home/kroll/mining/NarrativeIntelligence/src/narraint/queryengine/index/compute_reverse_index_predication.py", line 174, in <module>
    main()
  File "/home/kroll/mining/NarrativeIntelligence/src/narraint/queryengine/index/compute_reverse_index_predication.py", line 170, in main
    denormalize_predication_table(predication_id_min=args.predicate_id_minimum)
  File "/home/kroll/mining/NarrativeIntelligence/src/narraint/queryengine/index/compute_reverse_index_predication.py", line 141, in denormalize_predication_table
    PredicationInvertedIndex.bulk_insert_values_into_table(session, insert_list, check_constraints=False)
  File "/home/kroll/mining/NarrativeIntelligence/lib/KGExtractionToolbox/src/kgextractiontoolbox/backend/models.py", line 101, in bulk_insert_values_into_table
    postgres_copy_insert(session, values, cls.__tablename__)
  File "/home/kroll/mining/NarrativeIntelligence/lib/KGExtractionToolbox/src/kgextractiontoolbox/backend/models.py", line 66, in postgres_copy_insert
    cursor.copy_from(memory_file, table_name, sep='\t', columns=attribute_keys)
psycopg2.errors.IndexCorrupted: FEHLER:  table tid from new index tuple (835912,18) cannot find insert offset between offsets 2 and 8 of block 5716 in index "ix_predication_inverted_index_subject_id"
CONTEXT:  COPY predication_inverted_index, Zeile 22871

```

**Comment by HermannKroll** [comment]
I assume that the live service has affected the index on the table im some way... Maybe we need to lock the whole table until the update is done. The same would apply to compute_inverted_tag_index.py

**Comment by HermannKroll** [comment]
Solution was to recreate and recompute tables.

**Comment by ir0ntr0nik** [comment]
Sources:
- https://www.postgresql.org/docs/current/sql-lock.html
- https://www.postgresql.org/docs/current/explicit-locking.html
- https://stackoverflow.com/questions/77164201/sqlalchemy-2-0-option-for-lock-table

> Solution: lock table while inserting data. Commit afterward to unlock the table.  
> Problem: this is a PostgreSQL-only problem, so we have to check prior which underlying db is used.

> **EXCLUSIVE MODE**:  
    This mode allows only concurrent ACCESS SHARE locks, i.e., only reads from 
    the table can proceed in parallel with a transaction holding this lock mode.

Example for `compute_reverse_index_predication.py`.
```python
from sqlalchemy import text

if SessionExtended.is_postgres:
    session.execute(text("LOCK TABLE " + PredicationInvertedIndex.__tablename__ + " IN EXCLUSIVE MODE"))
# ... indexing code ...
session.commit() # unlock the table when finished
```
